// Generated by tools/build_gamedata.py - do not edit by hand
window.PBA_GAMES = {
 "697f6a08ef130744478db916": {
  "geniallyId": "697f6a08ef130744478db916",
  "title": "Luna et le grimoire des cartes",
  "lang": "fr",
  "total": 28,
  "slides": [
   {
    "id": "25be3f38-4674-42cb-9655-b9f3a6fb3cea",
    "order": 1,
    "name": "COVER",
    "popup": false,
    "texts": [
     "À la découverte du Petit Bridge",
     "Luna et le grimoire des cartes",
     "DÉMARRER"
    ]
   },
   {
    "id": "75f3916a-294d-4169-8f49-e58c0507c8bd",
    "order": 2,
    "name": "MENU",
    "popup": false,
    "texts": [
     "À l’école de la Magie, Luna ouvre le grimoire des cartes du Petit Bridge. Pour le compléter, elle doit réussir 4 leçons. À chaque étape de son apprentissage, Luna gagnera des potions magiques. Quand toutes les potions seront réunies, elle aura percé le mystère du Petit Bridge.",
     "Le grimoire des cartes",
     "Le grimoire du Petit Bridge"
    ]
   },
   {
    "id": "2fe009a2-dc3e-41d3-9e23-4413934cfdb4",
    "order": 3,
    "name": "MENU 1",
    "popup": false,
    "texts": [
     "Cette première leçon emmène Luna dans la Forêt des Premiers Pas. Dans cette forêt, elle devra répondre à des questions pour découvrir les cartes, les joueurs et apprendre à jouer avec un partenaire. Si Luna réussit toutes les épreuves de la forêt, elle obtiendra la Potion des Fondations. Es-tu prêt.e à l’aider ?",
     "Leçon 01",
     "Le grimoire du Petit Bridge"
    ]
   },
   {
    "id": "75b307ab-cec5-4c6a-ac2f-397a5b9c22ab",
    "order": 4,
    "name": "1.1",
    "popup": false,
    "texts": [
     "Question 1/4",
     "Voici les cartes du jeu Petit Bridge"
    ],
    "activity": {
     "type": "QUIZ_ACTIVITY",
     "question": "Combien y a-t-il de familles (couleurs) dans le jeu de cartes du Petit Bridge ?",
     "answers": [
      {
       "text": "1 famille",
       "correct": false,
       "order": null
      },
      {
       "text": "2 familles",
       "correct": false,
       "order": null
      },
      {
       "text": "4 familles",
       "correct": true,
       "order": null
      },
      {
       "text": "5 familles",
       "correct": false,
       "order": null
      }
     ],
     "feedbackOk": "Bravo !",
     "feedbackKo": "Attention ! Regarde bien les cartes affichées. Combien de couleurs différentes vois-tu ?"
    }
   },
   {
    "id": "551f03f3-bd02-4386-a734-26c2fc9fea5e",
    "order": 5,
    "name": "1.2",
    "popup": false,
    "texts": [
     "Les cartes sont rangées dans l'ordre croissant de la plus faible à la plus forte",
     "Question 2/4"
    ],
    "activity": {
     "type": "QUIZ_ACTIVITY",
     "question": "Quelle est la carte la plus forte dans une couleur ?",
     "answers": [
      {
       "text": "le 1",
       "correct": false,
       "order": null
      },
      {
       "text": "le 9",
       "correct": false,
       "order": null
      },
      {
       "text": "le 10",
       "correct": true,
       "order": null
      },
      {
       "text": "le 5",
       "correct": false,
       "order": null
      }
     ],
     "feedbackOk": "Bravo !",
     "feedbackKo": "Attention ! Regarde bien les cartes affichées. Quelle est la carte avec le nombre le plus grand ?"
    }
   },
   {
    "id": "412011e6-82c8-4ec9-93bf-a955dc92d170",
    "order": 6,
    "name": "1.3",
    "popup": false,
    "texts": [
     "Au bridge, on joue à deux contre deux. Les partenaires sont en face l’un de l’autre, autour d’un tapis sur lequel sont indiqués les points cardinaux.",
     "Question 3/4"
    ],
    "activity": {
     "type": "QUIZ_ACTIVITY",
     "question": "Qui est le partenaire de Luna, en Nord ?",
     "answers": [
      {
       "text": "Sud",
       "correct": true,
       "order": null
      },
      {
       "text": "Ouest",
       "correct": false,
       "order": null
      },
      {
       "text": "Est",
       "correct": false,
       "order": null
      }
     ],
     "feedbackOk": "Bravo !",
     "feedbackKo": "Attention ! Regarde bien l'image. Quel est le joueur placé en face du joueur Nord ?"
    }
   },
   {
    "id": "13eed9f3-c1c2-4e60-a09f-801f26b88141",
    "order": 7,
    "name": "1.4",
    "popup": false,
    "texts": [
     "Question 4/4"
    ],
    "activity": {
     "type": "FILL_IN_THE_BLANKS_ACTIVITY",
     "question": "Remplissez les blancs avec les bonnes réponses.",
     "answers": [
      {
       "text": "partenaire",
       "correct": false,
       "order": 3
      },
      {
       "text": "équipe",
       "correct": false,
       "order": 2
      },
      {
       "text": "Ouest",
       "correct": false,
       "order": 5
      },
      {
       "text": "Est",
       "correct": false,
       "order": 4
      },
      {
       "text": "10",
       "correct": false,
       "order": 1
      },
      {
       "text": "40",
       "correct": false,
       "order": 0
      }
     ],
     "feedbackOk": "Bravo ! Tu es prêt.e pour la suite des aventures",
     "feedbackKo": "Attention ! Aide toi des images..."
    }
   },
   {
    "id": "7ba0dff2-a163-4d1e-be21-f14708169bad",
    "order": 8,
    "name": "CORRECT 1",
    "popup": false,
    "texts": [
     "Continue",
     "Tu as découvert le matériel pour jouer au Petit Bridge. Tu permets à Luna de récupérer la Potion des Fondations.",
     "Bravo!",
     "La potion des Fondations"
    ]
   },
   {
    "id": "c78e738d-13ea-4403-b39f-b5aa21e14891",
    "order": 9,
    "name": "MENU 2",
    "popup": false,
    "texts": [
     "La deuxième leçon conduit Luna dans la Grotte des Jeux Secrets. Dans cette grotte mystérieuse, elle devra apprendre à jouer une carte,à comprendre comment gagner une levée et à savoir quoi faire quand elle n’a pas la bonne couleur. Si Luna réussit toutes les épreuves de la grotte, elle obtiendra la Potion des Levées",
     "Leçon 02",
     "Le grimoire du Petit Bridge"
    ]
   },
   {
    "id": "22c81fcd-2d61-4730-a7c2-25ec0b84953a",
    "order": 10,
    "name": "2.1",
    "popup": false,
    "texts": [
     "Ouest est le joueur qui a distribué les cartes. Il entame et pose la première carte. Il met un 7 vert. Tous les autres joueurs mettent une carte verte. Parmi les cartes vertes de Luna, choisis toi aussi une carte et pose la sur la table.",
     "Jeu de Luna",
     "Question 1/4",
     "Règle 1"
    ]
   },
   {
    "id": "5968dea4-b0a6-4f89-80fb-c5b0faa48f3b",
    "order": 11,
    "name": "2.2",
    "popup": false,
    "texts": [
     "Règle 2",
     "Question 2/4",
     "Une carte jaune a été posée en premier sur la table. Tous les joueurs ont joué une carte jaune de leur jeu."
    ],
    "activity": {
     "type": "QUIZ_ACTIVITY",
     "question": "À ton avis, qui a gagné la levée ?",
     "answers": [
      {
       "text": "Est",
       "correct": false,
       "order": null
      },
      {
       "text": "Nord",
       "correct": true,
       "order": null
      },
      {
       "text": "Ouest",
       "correct": false,
       "order": null
      },
      {
       "text": "Sud",
       "correct": false,
       "order": null
      }
     ],
     "feedbackOk": "Bravo !",
     "feedbackKo": "Attention ! Regarde bien qui a posé la carte la plus forte."
    }
   },
   {
    "id": "79a07f39-4f31-4642-bdff-5d22879978b3",
    "order": 12,
    "name": "2.3",
    "popup": false,
    "texts": [
     "Jeu de Luna",
     "Question 3/4",
     "Nord a gagné la levée avec le 8 jaune. C'est lui qui rejoue. Il pose maintenant un 2 rouge. Est pose une carte rouge. Luna n'a pas de carte rouge. Parmi les cartes de son jeu, choisis une carte à poser sur la table.",
     "Règle 3"
    ]
   },
   {
    "id": "39e0481f-2b3a-484a-b70a-b7116203e68a",
    "order": 13,
    "name": "2.4",
    "popup": false,
    "texts": [
     "Question 4/4"
    ],
    "activity": {
     "type": "FILL_IN_THE_BLANKS_ACTIVITY",
     "question": "Remplissez les blancs avec les bonnes réponses.",
     "answers": [
      {
       "text": "rejoue.",
       "correct": false,
       "order": 5
      },
      {
       "text": "défausse",
       "correct": false,
       "order": 4
      },
      {
       "text": "couleur",
       "correct": false,
       "order": 3
      },
      {
       "text": "forte",
       "correct": false,
       "order": 2
      },
      {
       "text": "levée",
       "correct": false,
       "order": 1
      },
      {
       "text": "carte",
       "correct": false,
       "order": 0
      }
     ],
     "feedbackOk": "Bravo ! Tu es prêt.e pour la suite des aventures",
     "feedbackKo": "Attention ! Rappelle toi des règles que l'on a découvert ensemble..."
    }
   },
   {
    "id": "fb64b39c-e682-49e0-b54c-3d6dedfc3489",
    "order": 14,
    "name": "CORRECT 2",
    "popup": false,
    "texts": [
     "La potion des Levées",
     "Continue",
     "Tu as appris comment jouer les cartes au Petit Bridge et gagner une levée. Tu permets à Luna de récupérer la Potion des Levées .",
     "Bravo !"
    ]
   },
   {
    "id": "b2c34569-5e6d-4e01-89ea-b6bb11a61749",
    "order": 15,
    "name": "MENU 3",
    "popup": false,
    "texts": [
     "Luna entre maintenant dans la Salle des duos magiques. Dans cette salle, elle va apprendre une règle très importante du Petit Bridge : on ne joue jamais seul. Pour réussir cette leçon, Luna devra comprendre comment jouer avec son partenaire, gagner des levées ensemble et aider son équipe. Si elle réussit toutes les épreuves de la salle, elle pourra récupérer la Potion des partenaires . Es-tu prêt.e à l’aider à jouer en équipe ?",
     "Leçon 03",
     "Le grimoire du Petit Bridge"
    ]
   },
   {
    "id": "7ff1c552-96fe-4167-a102-1094b6c9b971",
    "order": 16,
    "name": "3.1",
    "popup": false,
    "texts": [
     "Ce n'est pas la bonne réponse. Regarde bien la carte posée par ton partenaire en Nord. Recommence !",
     "Règle 4",
     "Luna a démarré une partie de Petit Bridge avec ses camarades de classe. Quelle carte conseilles-tu à Luna, placée en Sud, de jouer ?",
     "Question 1/4"
    ]
   },
   {
    "id": "d287bcb6-1727-49a3-aded-b2ec30e8e7f4",
    "order": 17,
    "name": "3.2",
    "popup": false,
    "texts": [
     "Bravo ! Ton partenaire ne peut pas gagner la levée avec sa carte. À toi de mettre ton 8 pour faire gagner ton équipe !",
     "Ce n'est pas la bonne réponse. Regarde bien la carte posée par ton partenaire en Nord. Recommence !",
     "Question 2/4",
     "Luna a démarré une partie de Petit Bridge avec ses camarades de classe. Quelle carte conseilles-tu à Luna, placée en Sud, de jouer ?"
    ]
   },
   {
    "id": "691201ac-7bc1-48de-9c26-e21d65a60c6c",
    "order": 18,
    "name": "3.3",
    "popup": false,
    "texts": [
     "Ce n'est pas la bonne réponse. Observe bien l'ensemble des cartes restant dans les mains de chaque joueur. Recommence !",
     "Règle 5",
     "Question 3/4",
     "Le partenaire de Luna joue le 8 jaune. À ton avis, que jouerais-tu si tu étais en Est ? Que jouerait Luna, placée en Sud ?"
    ]
   },
   {
    "id": "6f08499d-7e99-43d5-bccc-3d196fd56353",
    "order": 19,
    "name": "3.4",
    "popup": false,
    "texts": [
     "Question 4/4"
    ],
    "activity": {
     "type": "FILL_IN_THE_BLANKS_ACTIVITY",
     "question": "Remplissez les blancs avec les bonnes réponses.",
     "answers": [
      {
       "text": "partenaire",
       "correct": false,
       "order": 1
      },
      {
       "text": "équipe",
       "correct": false,
       "order": 0
      },
      {
       "text": "perdre",
       "correct": false,
       "order": 5
      },
      {
       "text": "grosse",
       "correct": false,
       "order": 2
      },
      {
       "text": "gaspiller",
       "correct": false,
       "order": 3
      },
      {
       "text": "fin",
       "correct": false,
       "order": 4
      }
     ],
     "feedbackOk": "Bravo ! Tu es prêt.e pour la suite des aventures",
     "feedbackKo": "Attention ! Rappelle toi des règles que l'on a découvert ensemble..."
    }
   },
   {
    "id": "da5cbf73-37db-4a0d-a13b-634d7c05c95a",
    "order": 20,
    "name": "CORRECT 3",
    "popup": false,
    "texts": [
     "Tu as appris à jouer avec ton partenaire au Petit Bridge. Tu sais maintenant qu’on joue ensemble pour gagner des levées. Tu permets à Luna de récupérer la Potion des Partenaires .",
     "La potion des Partenaires",
     "Bravo !",
     "Continue"
    ]
   },
   {
    "id": "f3557583-fb65-4d32-8894-a9569affd408",
    "order": 21,
    "name": "MENU 3 Copy",
    "popup": false,
    "texts": [
     "Luna entre dans la Bibliothèque des Dernières Leçons. Ici, un joueur pose ses cartes face visible sur la table : c’est l’endormi.Son partenaire devient alors le pilote de l’équipe et décide des cartes à jouer pour les deux joueurs. Si Luna réussit cette épreuve, elle récupérera la dernière potiondu Grimoire du Petit Bridge : la Potion de l’Endormi . Es-tu prêt.e à l’aider ?",
     "Leçon 04",
     "Le grimoire du Petit Bridge"
    ]
   },
   {
    "id": "12dfc389-cdad-4df8-ae08-089c67f77b00",
    "order": 22,
    "name": "4.1",
    "popup": false,
    "texts": [
     "Tu joues pour Ouest et pose le 8 vert sur la table. Le jeu de l'endormi se dévoile et Luna joue pour son partenaire. Pose la carte demandée sur la table et clique sur VÉRIFICATION",
     "Pose le 4 vert !",
     "Clique ICI",
     "Règle 6",
     "Question 1/4"
    ]
   },
   {
    "id": "30613d8b-9fb3-48af-b18b-448e79f97df6",
    "order": 23,
    "name": "4.3",
    "popup": false,
    "texts": [
     "Question 2/4"
    ],
    "activity": {
     "type": "IMAGE_ACTIVITY",
     "question": "Nord est endormi. Comment jouerais-tu à la place d'Est ?",
     "answers": [
      {
       "text": "",
       "correct": true,
       "order": null
      },
      {
       "text": "",
       "correct": false,
       "order": null
      }
     ],
     "feedbackOk": "",
     "feedbackKo": "Non, ce n'est pas le meilleur choix."
    }
   },
   {
    "id": "9f7caa94-e14b-4d42-a5b8-a3dc9e5916e8",
    "order": 24,
    "name": "4.3",
    "popup": false,
    "texts": [
     "Question 3/4",
     "C'est à Luna de poser une carte. Elle joue avec le jeu de l'Endormi en Nord. Trouve l'ordre dans lequel elle doit jouer ses cartes pour que son équipe gagne 4 levées sans connaitre les cartes des adversaires.",
     "Attention, tu n'as pas commencé par la bonne carte. Recommence."
    ]
   },
   {
    "id": "0c33ceb9-bde4-435e-8df2-b19f61a4670f",
    "order": 25,
    "name": "4.4",
    "popup": false,
    "texts": [
     "Question 4/4"
    ],
    "activity": {
     "type": "FILL_IN_THE_BLANKS_ACTIVITY",
     "question": "Remplissez les blancs avec les bonnes réponses.",
     "answers": [
      {
       "text": "endormi",
       "correct": false,
       "order": 2
      },
      {
       "text": "visible",
       "correct": false,
       "order": 3
      },
      {
       "text": "entame",
       "correct": false,
       "order": 0
      },
      {
       "text": "décide",
       "correct": false,
       "order": 4
      },
      {
       "text": "gauche",
       "correct": false,
       "order": 1
      }
     ],
     "feedbackOk": "Bravo ! Tu es prêt.e pour la suite des aventures",
     "feedbackKo": "Attention ! Rappelle toi des règles que l'on a découvert ensemble..."
    }
   },
   {
    "id": "49b9a96c-b21b-4eac-ab36-a0c339336146",
    "order": 26,
    "name": "CORRECT 4",
    "popup": false,
    "texts": [
     "Tu as aidé Luna à récupérer la dernière potion : la Potion de l'Endormi . Luna a terminé toutes les leçons du Grimoire du Petit Bridge. Elle connait les règles essentielles du jeu : les cartes, les levées, le jeu d'équipe et le rôle de l'endormi.",
     "FÉLICIATIONS !",
     "Le grimoire du Petit Bridge"
    ]
   },
   {
    "id": "1a943fe1-d2cc-4eab-952d-7f9de781cb39",
    "order": 27,
    "name": "FINAL",
    "popup": false,
    "texts": [
     "Il est maintenant temps de passer au jeu réel !"
    ]
   },
   {
    "id": "88761768-1922-4696-bde4-2cbd461f53f9",
    "order": 28,
    "name": "EXIT",
    "popup": false,
    "texts": [
     "Je continue",
     "J'arrête",
     "Si tu quittes le jeu maintenant, tu ne découvriras pas tous les secrets du Petit Bridge.",
     "Es-tu sur de vouloir arrêter l'aventure ?"
    ]
   },
   {
    "id": "273005c0-457f-40dd-b1a0-13b64ccc4793",
    "order": 29,
    "name": "Copie Copie",
    "popup": true,
    "texts": [
     "Réponse à l'exercice : Ici Est ne peut pas gagner donc il doit mettre sa petite carte. Sud doit jouer le 10 jaune sinon Ouest va gagner avec son 9 jaune.",
     "Règle 5",
     "Bravo ! 🎉",
     "Attention, jouer sans gaspiller ne veut pas forcément dire garder ses grosses cartes pour la fin !"
    ]
   },
   {
    "id": "28f5ed17-70d2-4029-b796-0f93a979520c",
    "order": 30,
    "name": "Copie Copie",
    "popup": true,
    "texts": [
     "Exemple : Si la couleur demandée est du rouge et que je n'ai pas cette couleur dans mon jeu, mon 9 jaune ne pourra pas gagner la levée. Il est préférable de mettre une petite carte comme le 2 vert par exemple.",
     "Règle 3",
     "Bravo ! 🎉",
     "Si on n’a pas de carte de la couleur demandée, on se \"défausse\" d’une carte d’une autre couleur mais elle ne peut pas gagner la levée."
    ]
   },
   {
    "id": "4ae95e6b-283e-4783-97bb-5249aa12242e",
    "order": 31,
    "name": "Copie",
    "popup": true,
    "texts": [
     "Le Petit Bridge est un jeu d'équipe : il faut jouer sans gaspiller !",
     "Règle 4",
     "Bravo ! 🎉",
     "Je joue en équipe. Je dois être attentif aux cartes jouées par mon partenaire. S'il va gagner la levée, la meilleure tactique n'est pas de jouer ma plus grosse carte. Je peux la garder pour plus tard pour faire une autre levée."
    ]
   },
   {
    "id": "58e3a383-70dc-491a-a840-0f77dacf96ec",
    "order": 32,
    "name": "Copie",
    "popup": true,
    "texts": [
     "Exemple : Si la première carte posée sur la table est une carte verte alors on est obligé de jouer une carte verte présente dans son jeu.",
     "Règle 1",
     "Bravo ! 🎉",
     "Il faut jouer la couleur demandée par la première carte posée sur la table."
    ]
   },
   {
    "id": "d3d0d916-eb44-4b1c-827c-e2b2af58e483",
    "order": 33,
    "name": "Copie",
    "popup": true,
    "texts": [
     "Mémo Une levée est l'ensemble des 4 cartes jouées par chaque joueur. A chaque partie, il y a, au maximum, 10 levées à réaliser.",
     "Règle 2",
     "Bravo ! 🎉",
     "Le joueur qui a posé la plus forte carte gagne la levée. Il rejoue pour la levée suivante.",
     "Le but du jeu est de faire plus de levées que les adversaires."
    ]
   },
   {
    "id": "f9cedbec-bc0d-45ed-871a-ac5d853e2fdf",
    "order": 34,
    "name": "Copie Copie Copie Copie",
    "popup": true,
    "texts": [
     "Entame : c'est la première carte jouée de la partie.",
     "Règle 6",
     "Bravo ! 🎉",
     "Lorsque la carte d'entame est posée sur la table, le joueur à gauche étale son jeu face visible. Il devient l' Endormi pour la durée de la partie. C'est son partenaire qui décide et lui indique quelles cartes jouer."
    ]
   }
  ]
 },
 "6999b0b9d1e83ea5a328b462": {
  "geniallyId": "6999b0b9d1e83ea5a328b462",
  "title": "BridgeBot",
  "lang": "fr",
  "total": 34,
  "slides": [
   {
    "id": "25be3f38-4674-42cb-9655-b9f3a6fb3cea",
    "order": 1,
    "name": "COVER",
    "popup": false,
    "texts": [
     "Le protocole Mini Bridge",
     "Mission BridgeBot",
     "Démarrer"
    ]
   },
   {
    "id": "75f3916a-294d-4169-8f49-e58c0507c8bd",
    "order": 2,
    "name": "MENU",
    "popup": false,
    "texts": [
     "Dans un futur proche, les humains ont confié les jeux de stratégie à une intelligence artificielle centrale : BridgeBot. Mais des robots malveillants ont infiltré son système. Ils ont pris le contrôle de BridgeBot et l’ont corrompue. Désormais, elle applique les règles sans les comprendre et perturbe toutes les parties. C’est là que vous intervenez. Vous êtes recrutés comme agents de reprogrammation . Votre mission : restaurer les protocoles essentiels du Mini Bridge, neutraliser les robots corrompus et redonner à BridgeBot sa capacité à réfléchir et jouer en équipe. Serez-vous capables de reprendre le contrôle du système avant qu’il ne soit trop tard ?",
     "Le protocole Mini Bridge"
    ]
   },
   {
    "id": "24c272ea-52d9-4928-a9e8-d5833f369c88",
    "order": 3,
    "name": "MISSION 1",
    "popup": false,
    "texts": [
     "Protocole : Fondations du système",
     "MISSION 1 — Salle d’initialisation",
     "BridgeBot a été piratée. Les robots corrompus ont désactivé les bases du Mini Bridge. Le système ne reconnaît plus correctement les cartes, les joueurs ni les positions. Votre première mission consiste à réactiver le Module Fondations. Dans la Salle d’initialisation, vous devrez : i dentifier le matériel du Mini Bridge, c omprendre la distribution des cartes, r eplacer correctement les joueurs et r éactiver la notion d’équipe Si vous réussissez, vous récupérerez le Module Fondations et stabiliserez le cœur du système."
    ]
   },
   {
    "id": "50c01e57-811e-4701-b927-ac1c319cfb30",
    "order": 4,
    "name": "MISSION 1.1",
    "popup": false,
    "texts": [
     "Voici les cartes du Mini Bridge",
     "Question 1/4"
    ],
    "activity": {
     "type": "QUIZ_ACTIVITY",
     "question": "Combien y a-t-il de couleurs dans le jeu de cartes du Mini Bridge ?",
     "answers": [
      {
       "text": "4 couleurs",
       "correct": true,
       "order": null
      },
      {
       "text": "5 couleurs",
       "correct": false,
       "order": null
      },
      {
       "text": "1 couleur",
       "correct": false,
       "order": null
      },
      {
       "text": "2 couleurs",
       "correct": false,
       "order": null
      }
     ],
     "feedbackOk": "Bravo !",
     "feedbackKo": "Attention ! Clique sur l'oeil pour avoir un indice."
    }
   },
   {
    "id": "392bc879-3c71-4d3e-b715-325c2e96b76e",
    "order": 5,
    "name": "MISSION 1.2",
    "popup": false,
    "texts": [
     "Question 2/4",
     "Les cartes sont rangées dans l'ordre croissant de la plus faible à la plus forte"
    ],
    "activity": {
     "type": "QUIZ_ACTIVITY",
     "question": "Quelle est la carte la plus forte dans une couleur ?",
     "answers": [
      {
       "text": "l'As",
       "correct": true,
       "order": null
      },
      {
       "text": "le 10",
       "correct": false,
       "order": null
      },
      {
       "text": "le 2",
       "correct": false,
       "order": null
      },
      {
       "text": "le Roi",
       "correct": false,
       "order": null
      }
     ],
     "feedbackOk": "Bravo !",
     "feedbackKo": "Attention ! Regarde bien les cartes affichées."
    }
   },
   {
    "id": "b29c701a-c65d-4920-b3dd-71301d2cdaed",
    "order": 6,
    "name": "MISSION 1.3",
    "popup": false,
    "texts": [
     "Question 3/4",
     "Au bridge, on joue à deux contre deux. Les partenaires sont en face l’un de l’autre, autour d’un tapis sur lequel sont indiqués les points cardinaux."
    ],
    "activity": {
     "type": "QUIZ_ACTIVITY",
     "question": "Qui est le partenaire de Nord ?",
     "answers": [
      {
       "text": "Est",
       "correct": false,
       "order": null
      },
      {
       "text": "Sud",
       "correct": true,
       "order": null
      },
      {
       "text": "Ouest",
       "correct": false,
       "order": null
      }
     ],
     "feedbackOk": "Bravo !",
     "feedbackKo": "Attention ! Regarde bien l'image. Quel est le joueur placé en face du joueur Nord ?"
    }
   },
   {
    "id": "dae35015-e12b-4fe8-ad4d-b615e164d900",
    "order": 7,
    "name": "MISSION 1.4",
    "popup": false,
    "texts": [
     "Question 4/4"
    ],
    "activity": {
     "type": "FILL_IN_THE_BLANKS_ACTIVITY",
     "question": "Remplissez les blancs avec les bonnes réponses.",
     "answers": [
      {
       "text": "Est",
       "correct": false,
       "order": 4
      },
      {
       "text": "13",
       "correct": false,
       "order": 1
      },
      {
       "text": "52",
       "correct": false,
       "order": 0
      },
      {
       "text": "équipe",
       "correct": false,
       "order": 2
      },
      {
       "text": "Ouest",
       "correct": false,
       "order": 5
      },
      {
       "text": "partenaire",
       "correct": false,
       "order": 3
      }
     ],
     "feedbackOk": "Bravo ! Vous êtes prêt.e.s pour la suite des aventures !",
     "feedbackKo": "Attention ! Aide toi des images..."
    }
   },
   {
    "id": "70c19774-f41b-42ba-a75e-8e93ff5b29ff",
    "order": 8,
    "name": "MISSION 1 SUCCES",
    "popup": false,
    "texts": [
     "Vous avez découvert le matériel pour jouer au Mini Bridge. Vous permettez de restaurer le Module Fondations de Bridgebot !",
     "Bravo !",
     "Continue",
     "Module Fondations"
    ]
   },
   {
    "id": "0ba7eb8d-2f8f-43cb-983f-3b5989a496fc",
    "order": 9,
    "name": "MISSION 2",
    "popup": false,
    "texts": [
     "Protocole : Plis et Règles",
     "MISSION 2 — Salle de simulation",
     "Les robots corrompus ont brouillé les règles de jeu. BridgeBot ne sait plus comment jouer une carte correctement. Dans la Salle de simulation, vous devrez : r especter la couleur demandée, c omprendre comment se gagne une levée et i dentifier la carte la plus forte. Chaque bonne décision réactivera une ligne de code. À la fin de la mission, vous restaurerez le Module des Levées .",
     "Module Fondations"
    ]
   },
   {
    "id": "62f19c7d-478e-420c-953d-8a564db9d911",
    "order": 10,
    "name": "MISSION 2.1",
    "popup": false,
    "texts": [
     "Question 1/4",
     "Ouest est le joueur qui a distribué les cartes. Il entame et pose la première carte. Il met un le Roi de ♦️. Tous les autres joueurs mettent une carte à ♦️. Parmi vos cartes à ♦️, choisissez vous aussi une carte et posez la sur la table.",
     "Règle 1"
    ]
   },
   {
    "id": "d0a88456-92a3-4349-aee4-c7eb0a85a3ad",
    "order": 11,
    "name": "MISSION 2.2",
    "popup": false,
    "texts": [
     "Question 2/4",
     "Une carte à ♠️ a été posée en premier sur la table. Tous les joueurs ont joué une carte à ♠️ de leur jeu.",
     "Règle 2"
    ],
    "activity": {
     "type": "QUIZ_ACTIVITY",
     "question": "À votre avis, qui a gagné la levée ?",
     "answers": [
      {
       "text": "Est",
       "correct": false,
       "order": null
      },
      {
       "text": "Nord",
       "correct": true,
       "order": null
      },
      {
       "text": "Ouest",
       "correct": false,
       "order": null
      },
      {
       "text": "Sud",
       "correct": false,
       "order": null
      }
     ],
     "feedbackOk": "Bravo !",
     "feedbackKo": "Attention ! Regarde bien qui a posé la carte la plus forte."
    }
   },
   {
    "id": "1f5b78ad-8caa-414e-94f5-b35f0f9abcea",
    "order": 12,
    "name": "MISSION 2.3",
    "popup": false,
    "texts": [
     "Question 3/4",
     "Nord a gagné la levée avec l'As de ♠️. C'est lui qui rejoue. Il pose maintenant un 5 de ♥️. Est pose le 9 de ♥️. Vous n'avez pas de carte à ♥️. Parmi les cartes de votre jeu, choisissez une carte à poser sur la table.",
     "Règle 3"
    ]
   },
   {
    "id": "a7f00ca1-58e4-4cc1-81e4-8f010ef3b73f",
    "order": 13,
    "name": "MISSION 2.4",
    "popup": false,
    "texts": [
     "Question 4/4"
    ],
    "activity": {
     "type": "FILL_IN_THE_BLANKS_ACTIVITY",
     "question": "Remplissez les blancs avec les bonnes réponses.",
     "answers": [
      {
       "text": "défaussez",
       "correct": false,
       "order": 4
      },
      {
       "text": "carte",
       "correct": false,
       "order": 0
      },
      {
       "text": "levée",
       "correct": false,
       "order": 1
      },
      {
       "text": "forte",
       "correct": false,
       "order": 2
      },
      {
       "text": "rejoue.",
       "correct": false,
       "order": 5
      },
      {
       "text": "couleur",
       "correct": false,
       "order": 3
      }
     ],
     "feedbackOk": "Bravo ! Vous êtes prêt.e.s pour la suite des aventures !",
     "feedbackKo": "Attention ! Rappelle toi des règles que l'on a découvert ensemble..."
    }
   },
   {
    "id": "83c66b33-ffd5-4d61-8503-b7a4f8cc0bcd",
    "order": 14,
    "name": "MISSION 2 SUCESS",
    "popup": false,
    "texts": [
     "Continue",
     "Vous avez appris comment jouer les cartes au Mini Bridge et gagner une levée. Vous restaurez le Module des Levées.",
     "Bravo !",
     "Module des Levées"
    ]
   },
   {
    "id": "2757ec9a-0d4b-4ca9-8d21-24da3b5d2eea",
    "order": 15,
    "name": "MISSION 3",
    "popup": false,
    "texts": [
     "Protocole : Jeu d'équipe",
     "MISSION 3 — Salle des stratégies",
     "BridgeBot joue désormais seule… Elle a oublié qu’au Mini Bridge, on joue à deux contre deux. Dans la Salle des stratégies, vous devrez : o bserver les cartes de votre partenaire, d écider quand soutenir, é viter de gaspiller une carte forte et c omprendre qu’on ne joue pas seulement pour soi. Si vous réussissez, vous réactiverez le Module Coopération et neutraliserez un robot corrompu supplémentaire.",
     "Module des Levées",
     "Module Fondations"
    ]
   },
   {
    "id": "f886a5a6-746a-4a30-ab65-39968aa542d7",
    "order": 16,
    "name": "MISSION 3.1",
    "popup": false,
    "texts": [
     "Question 1/4",
     "BridgeBot a démarré une partie de Mini Bridge. Quelle carte lui conseillez-vous de jouer ?",
     "Ce n'est pas la bonne réponse. Regarde bien la carte posée par ton partenaire en Nord. Recommence !",
     "Règle 4"
    ]
   },
   {
    "id": "a25d9c4c-6b09-4230-a7e6-fa4f4ac26198",
    "order": 17,
    "name": "MISSION 3.2",
    "popup": false,
    "texts": [
     "Question 2/4",
     "BridgeBot a démarré une partie de Mini Bridge. Quelle carte lui conseillez-vous de jouer ?",
     "Bravo ! Ton partenaire ne peut pas gagner la levée avec sa carte. À toi de mettre ta Dame de ♦️ pour faire gagner ton équipe !",
     "Ce n'est pas la bonne réponse. Regarde bien la carte posée par ton partenaire en Nord. Recommence !"
    ]
   },
   {
    "id": "408c9316-b954-425c-9aaf-d0c4cffc4f03",
    "order": 18,
    "name": "MISSION 3.3",
    "popup": false,
    "texts": [
     "Question 3/4",
     "BridgeBot a démarré une partie de Mini Bridge. Quelle carte conseillez-vous à Est et à Sud de jouer ?",
     "Ce n'est pas la bonne réponse. Observe bien l'ensemble des cartes restant dans les mains de chaque joueur. Recommence !",
     "Règle 5"
    ]
   },
   {
    "id": "6e78eea0-10b2-493c-b9ff-638a92577ee2",
    "order": 19,
    "name": "MISSION 3.4",
    "popup": false,
    "texts": [
     "Question 4/4"
    ],
    "activity": {
     "type": "FILL_IN_THE_BLANKS_ACTIVITY",
     "question": "Remplissez les blancs avec les bonnes réponses.",
     "answers": [
      {
       "text": "équipe",
       "correct": false,
       "order": 0
      },
      {
       "text": "partenaire",
       "correct": false,
       "order": 1
      },
      {
       "text": "perdre",
       "correct": false,
       "order": 5
      },
      {
       "text": "grosse",
       "correct": false,
       "order": 2
      },
      {
       "text": "gaspiller",
       "correct": false,
       "order": 3
      },
      {
       "text": "fin",
       "correct": false,
       "order": 4
      }
     ],
     "feedbackOk": "Bravo ! Vous êtes prêt.e.s pour la suite des aventures !",
     "feedbackKo": "Attention ! Rappelle toi des règles que l'on a découvert ensemble..."
    }
   },
   {
    "id": "6d701235-b927-4f1d-8139-ce8c25cccae4",
    "order": 20,
    "name": "MISSION 3 SUCESS",
    "popup": false,
    "texts": [
     "Continue",
     "Vous avez appris à jouer avec votre partenaire au Mini Bridge. Vous savez maintenant qu’on joue ensemble pour gagner des levées. Vous restaurez le Module Coopération.",
     "Bravo !",
     "Module Coopération"
    ]
   },
   {
    "id": "d6dbbffb-3aba-4ac6-ad5b-9bed4b1e639b",
    "order": 21,
    "name": "MISSION 4",
    "popup": false,
    "texts": [
     "Protocole : Endormi",
     "MISSION 4 — Salle du pilotage central",
     "Les robots ennemis ont désactivé le module le plus stratégique : l’Endormi. BridgeBot ne comprend plus qu’un joueur peut piloter les cartes de son partenaire lorsque celles-ci sont dévoilées. Dans cette dernière salle, vous devrez : i dentifier la carte d’entame, c omprendre le rôle de l’endormi, s avoir qu’il ne prend plus de décision, p iloter les deux jeux avec stratégie En restaurant ce dernier protocole, vous récupérerez le Module Endormi.",
     "Module Coopération",
     "Module des Levées",
     "Module Fondations"
    ]
   },
   {
    "id": "71497f16-6c41-4304-a27d-933852b5a254",
    "order": 22,
    "name": "MISSION 4.1",
    "popup": false,
    "texts": [
     "Ouest pose l'As de ♦️ sur la table. Le jeu de l'endormi se dévoile et vous jouez pour votre partenaire. Pose la carte demandée sur la table et clique sur VÉRIFICATION",
     "Pose le 6 de ♦️ !",
     "Clique ICI",
     "Question 1/4",
     "Règle 6"
    ]
   },
   {
    "id": "9c37de8b-42c7-41e6-9f33-8ef8bcbc8119",
    "order": 23,
    "name": "MISSION 4.2",
    "popup": false,
    "texts": [
     "Question 2/4"
    ],
    "activity": {
     "type": "IMAGE_ACTIVITY",
     "question": "Nord est endormi. Comment joueriez-vous à la place d'Est ?",
     "answers": [
      {
       "text": "",
       "correct": true,
       "order": null
      },
      {
       "text": "",
       "correct": false,
       "order": null
      }
     ],
     "feedbackOk": "Bravo !",
     "feedbackKo": "Non, ce n'est pas le meilleur choix."
    }
   },
   {
    "id": "b5e5643a-6448-400b-b374-e701ab972a50",
    "order": 24,
    "name": "MISSION 4.3",
    "popup": false,
    "texts": [
     "Question 3/4",
     "C'est à vous de poser une carte. Vous jouez avec le jeu de l'Endormi en Nord. Trouvez l'ordre dans lequel jouer vos cartes pour que votre équipe gagne 4 levées sans connaitre les cartes de vos adversaires.",
     "Attention, tu n'as pas commencé par la bonne carte. Recommence."
    ]
   },
   {
    "id": "4d55708b-1c18-42b2-92b9-7ef5a66b60ce",
    "order": 25,
    "name": "MISSION 4.4",
    "popup": false,
    "texts": [
     "Question 4/4"
    ],
    "activity": {
     "type": "FILL_IN_THE_BLANKS_ACTIVITY",
     "question": "Remplissez les blancs avec les bonnes réponses.",
     "answers": [
      {
       "text": "gauche",
       "correct": false,
       "order": 1
      },
      {
       "text": "visible",
       "correct": false,
       "order": 3
      },
      {
       "text": "décide",
       "correct": false,
       "order": 4
      },
      {
       "text": "entame",
       "correct": false,
       "order": 0
      },
      {
       "text": "endormi",
       "correct": false,
       "order": 2
      }
     ],
     "feedbackOk": "Bravo !",
     "feedbackKo": "Attention ! Rappelle toi des règles que l'on a découvert ensemble..."
    }
   },
   {
    "id": "637eb069-49db-4ed4-89c5-5dbf15e53e46",
    "order": 26,
    "name": "MISSION 4 SUCESS",
    "popup": false,
    "texts": [
     "Continue",
     "BridgeBot connait maintenant les règles essentielles du jeu : les cartes, les levées, le jeu d'équipe et le rôle de l'endormi. Vous restaurez le Module Endormi.",
     "Bravo !",
     "Module Coopération"
    ]
   },
   {
    "id": "7686455e-181b-4c9c-9f9e-bfa4b9b32428",
    "order": 27,
    "name": "MISSION 5",
    "popup": false,
    "texts": [
     "Protocole : Détermination du contrat",
     "MISSION 5 — Salle de projection",
     "Module Endormi",
     "Module Coopération",
     "Module des Levées",
     "Les robots corrompus ont saboté le module de prévision. BridgeBot joue les cartes… mais elle ne sait plus fixer d’objectif avant de commencer. Or au Mini Bridge, on ne joue pas au hasard. Avant même la première carte, l’équipe doit décider combien de levées elle pense pouvoir gagner. Dans la Salle de projection, vous devrez : o bserver les cartes de votre équipe, i dentifier vos forces, c ompter les levées probables, c hoisir un contrat réaliste, c omprendre qu’un contrat engage les deux partenaires. Chaque estimation correcte réactive une ligne du programme de planification. Si vous réussissez, vous restaurerez le Module Contrat . BridgeBot pourra de nouveau prévoir… avant d’agir.",
     "Module Fondations"
    ]
   },
   {
    "id": "815ab4f3-01f9-4054-9389-bb49e2a10967",
    "order": 28,
    "name": "MISSION 5.1",
    "popup": false,
    "texts": [
     "Question 1/4",
     "Les Honneurs",
     "As : 4 points Roi : 3 points Dame : 2 points Valet 1 point",
     "Maintenant, vous allez découvrir que certaines cartes ont une valeur. Il va falloir compter les points de votre jeu."
    ],
    "activity": {
     "type": "QUIZ_ACTIVITY",
     "question": "Détermine le nombre de points d'honneur de cette main.",
     "answers": [
      {
       "text": "15 points",
       "correct": false,
       "order": null
      },
      {
       "text": "14 points",
       "correct": false,
       "order": null
      },
      {
       "text": "13 points",
       "correct": false,
       "order": null
      },
      {
       "text": "12 points",
       "correct": true,
       "order": null
      }
     ],
     "feedbackOk": "Bravo !",
     "feedbackKo": "Regarde bien les points donnés à chaque Honneur."
    }
   },
   {
    "id": "24287775-cd60-416a-8f2a-6a39389991a5",
    "order": 29,
    "name": "MISSION 5.2",
    "popup": false,
    "texts": [
     "Question 2/4",
     "Les Honneurs",
     "As : 4 points Roi : 3 points Dame : 2 points Valet 1 point",
     "♠️ A 3 2 ♥️ 9 7 5 ♦️ 10 5 3 ♣️ R D 10 8",
     "♠️ V 10 9 6 ♥️ V 4 2 ♦️ D V 9 ♣️ 7 6 4",
     "♠️ 8 5 4 ♥️ A R D 10 ♦️ 8 6 4 ♣️ 9 3 2",
     "♠️ R D 7 ♥️ 8 6 3 ♦️ A R 7 2 ♣️ A V 5",
     "Règle 7"
    ],
    "activity": {
     "type": "QUIZ_ACTIVITY",
     "question": "Comptez les points de chaque joueur et déterminez l’équipe qui a le plus de points.",
     "answers": [
      {
       "text": "Équipe Est-Ouest",
       "correct": false,
       "order": null
      },
      {
       "text": "Équipe Nord-Sud",
       "correct": true,
       "order": null
      }
     ],
     "feedbackOk": "Bravo !",
     "feedbackKo": "Attention ! Nord a 9 pts, Sud 17 pts, Est 5 pts et Ouest 8 pts."
    }
   },
   {
    "id": "7ea4ae19-6f61-4f68-891a-7ed08d7661ba",
    "order": 30,
    "name": "MISSION 5.3",
    "popup": false,
    "texts": [
     "Question 3/4",
     "Règle 8",
     "Voici les points calculés : Nord : 9 points Sud : 17 points Equipe Nord-Sud : 26 points __ Est : 5 points Ouest : 8 points Equipe Est-Ouest : 14 points"
    ],
    "activity": {
     "type": "QUIZ_ACTIVITY",
     "question": "L'équipe majoritaire en point, va s'engager sur un contrat. Lequel ?",
     "answers": [
      {
       "text": "20 à 22 points - 7 levées",
       "correct": false,
       "order": null
      },
      {
       "text": "23 à 24 points - 8 levées",
       "correct": false,
       "order": null
      },
      {
       "text": "25 à 26 points - 9 levées",
       "correct": true,
       "order": null
      },
      {
       "text": "27 à 29 points - 10 levées",
       "correct": false,
       "order": null
      },
      {
       "text": "30 à 32 points - 11 levées",
       "correct": false,
       "order": null
      },
      {
       "text": "33 à 36 points - 12 levées",
       "correct": false,
       "order": null
      }
     ],
     "feedbackOk": "Bravo !",
     "feedbackKo": "Attention ! Regarde les points de l'équipe majoritaire."
    }
   },
   {
    "id": "67c44e35-27b4-47ef-b068-3516e3a472d9",
    "order": 31,
    "name": "MISSION 5.4",
    "popup": false,
    "texts": [
     "Question 4/4",
     "Les Honneurs",
     "As : 4 points Roi : 3 points Dame : 2 points Valet 1 point"
    ],
    "activity": {
     "type": "FILL_IN_THE_BLANKS_ACTIVITY",
     "question": "Remplissez les blancs avec les bonnes réponses.",
     "answers": [
      {
       "text": "l'entameur",
       "correct": false,
       "order": 5
      },
      {
       "text": "le déclarant",
       "correct": false,
       "order": 4
      },
      {
       "text": "8",
       "correct": false,
       "order": 3
      },
      {
       "text": "17",
       "correct": false,
       "order": 2
      },
      {
       "text": "23",
       "correct": false,
       "order": 1
      },
      {
       "text": "18",
       "correct": false,
       "order": 0
      }
     ],
     "feedbackOk": "Bravo !",
     "feedbackKo": "Aidez vous de la valeur des Honneurs et de l'indice."
    }
   },
   {
    "id": "81fceed7-5feb-48c4-a861-ee555460db5c",
    "order": 32,
    "name": "MISSION 5 SUCCESS",
    "popup": false,
    "texts": [
     "Mission accomplie, agents ! Vous avez réactivé le module Protection. Les robots corrompus ont été neutralisés et le système est sécurisé. BridgeBot est désormais de nouveau opérationnelle. Elle comprend les règles, coopère avec son partenaire et peut planifier ses actions avant de jouer. Grâce à vous, le Mini Bridge est sauvé. Le réseau est stable. Le programme est relancé. La partie peut commencer.",
     "Bravo !"
    ]
   },
   {
    "id": "a7c300e0-8afe-462f-b1c2-70e9645be4b0",
    "order": 33,
    "name": "FINAL",
    "popup": false,
    "texts": [
     "Il est maintenant temps de passer au jeu réel !"
    ]
   },
   {
    "id": "4f3a68ab-6306-43f1-85f3-c4108aafbf75",
    "order": 34,
    "name": "SORTIE",
    "popup": false,
    "texts": [
     "Si vous quittez le jeu maintenant, vous ne restaurerez pas BridgeBot et les secrets du Mini Bridge.",
     "Êtes-vous sûrs de vouloir arrêter l'aventure ?",
     "Je continue",
     "J'arrête"
    ]
   },
   {
    "id": "48384966-b026-4cc7-b471-7115ad86ba05",
    "order": 35,
    "name": "Copie Copie Copy",
    "popup": true,
    "texts": [
     "Réponse à l'exercice : Ici Est ne peut pas gagner donc il doit mettre sa petite carte. Sud doit jouer son As de ♠️ sinon Ouest va gagner avec son Roi de ♠️.",
     "Règle 5",
     "Bravo ! 🎉",
     "Attention, jouer sans gaspiller ne veut pas forcément dire garder ses grosses cartes pour la fin !"
    ]
   },
   {
    "id": "5770c88c-6dad-443c-bd95-27146b35f58b",
    "order": 36,
    "name": "Copie Copie Copy",
    "popup": true,
    "texts": [
     "Exemple : Si la couleur demandée est du ♥️ et que je n'ai pas cette couleur dans mon jeu, mon Roi de ♠️ ne pourra pas gagner la levée. Il est préférable de mettre une petite carte comme le 2 de ♣️ par exemple.",
     "Règle 3",
     "Bravo ! 🎉",
     "Si on n’a pas de carte de la couleur demandée, on se \"défausse\" d’une carte d’une autre couleur mais elle ne peut pas gagner la levée."
    ]
   },
   {
    "id": "62f493ba-1a5d-41fb-a261-e547ff37db54",
    "order": 37,
    "name": "",
    "popup": true,
    "texts": [
     "Il y a 40 points en tout dans le jeu à répartir entre les 2 équipes.",
     "Règle 7",
     "Bravo ! 🎉",
     "Avant de démarrer la partie, chaque joueur va compter les points de son jeu et les additionner avec ceux de son partenaire."
    ]
   },
   {
    "id": "8b023742-f1fb-45e9-98bf-758510772673",
    "order": 38,
    "name": "Copie Copy",
    "popup": true,
    "texts": [
     "Le Mini Bridge est un jeu d'équipe : il faut jouer sans gaspiller !",
     "Règle 4",
     "Bravo ! 🎉",
     "Je joue en équipe. Je dois être attentif aux cartes jouées par mon partenaire. S'il va gagner la levée, la meilleure tactique n'est pas de jouer ma plus grosse carte. Je peux la garder pour plus tard pour faire une autre levée."
    ]
   },
   {
    "id": "a2ebd7cf-6c3a-4bb9-bc25-2842813e0245",
    "order": 39,
    "name": "Copie Copie Copie Copie Copy",
    "popup": true,
    "texts": [
     "Entame : c'est la première carte jouée de la partie.",
     "Règle 6",
     "Bravo ! 🎉",
     "Lorsque la carte d'entame est posée sur la table, le joueur à gauche étale son jeu face visible. Il devient l' Endormi (on dit aussi le mort ) pour la durée de la partie. C'est son partenaire qui décide et lui indique quelles cartes jouer."
    ]
   },
   {
    "id": "c54e8840-1afd-4692-99dd-0f7cfcc2ad63",
    "order": 40,
    "name": "Copie Copy Copy",
    "popup": true,
    "texts": [
     "Exemple : Si la première carte posée sur la table est une carte à ♦️ alors on est obligé de jouer une carte à ♦️ présente dans son jeu.",
     "Règle 1",
     "Bravo ! 🎉",
     "Il faut jouer la couleur demandée par la première carte posée sur la table."
    ]
   },
   {
    "id": "cb91a57b-9ca4-4182-9eeb-bd7aa6aa7a58",
    "order": 41,
    "name": "Copie Copy",
    "popup": true,
    "texts": [
     "Mémo Une levée est l'ensemble des 4 cartes jouées par chaque joueur. A chaque partie, il y a, au maximum, 13 levées à réaliser.",
     "Règle 2",
     "Bravo ! 🎉",
     "Le joueur qui a posé la plus forte carte gagne la levée. Il rejoue pour la levée suivante.",
     "Le but du jeu est de faire plus de levées que les adversaires."
    ]
   },
   {
    "id": "fa35eda6-2353-47b7-a458-047e5beee455",
    "order": 42,
    "name": "Copy",
    "popup": true,
    "texts": [
     "20 - 21 - 22 points = 7 levées 23 - 24 points = 8 levées 25 - 26 points= 9 levées 27 - 28 - 29 points= 10 levées 30 - 31 - 32 points = 11 levées 33 - 34 - 35 - 36 points = 12 levées 37 - 38 - 39 - 40 points = 13 levées",
     "Règle 8",
     "Bravo ! 🎉",
     "L'équipe qui a le plus de points va s'engager sur un contrat de levées à réaliser. Pour le choisir, elle va s'aider de la table de décision ci-dessous"
    ]
   }
  ]
 }
};
