// Generated by tools/build_gamedata.py - do not edit by hand
window.PBA_GAMEDATA = {
 "geniallyId": "697f6a08ef130744478db916",
 "title": "Luna et le grimoire des cartes",
 "lang": "fr",
 "total": 28,
 "slides": [
  {
   "id": "25be3f38-4674-42cb-9655-b9f3a6fb3cea",
   "order": 1,
   "name": "COVER",
   "popup": false,
   "texts": [
    "À la découverte du Petit Bridge",
    "Luna et le grimoire des cartes",
    "DÉMARRER"
   ]
  },
  {
   "id": "75f3916a-294d-4169-8f49-e58c0507c8bd",
   "order": 2,
   "name": "MENU",
   "popup": false,
   "texts": [
    "À l’école de la Magie, Luna ouvre le grimoire des cartes du Petit Bridge. Pour le compléter, elle doit réussir 4 leçons. À chaque étape de son apprentissage, Luna gagnera des potions magiques. Quand toutes les potions seront réunies, elle aura percé le mystère du Petit Bridge.",
    "Le grimoire des cartes",
    "Le grimoire du Petit Bridge"
   ]
  },
  {
   "id": "2fe009a2-dc3e-41d3-9e23-4413934cfdb4",
   "order": 3,
   "name": "MENU 1",
   "popup": false,
   "texts": [
    "Cette première leçon emmène Luna dans la Forêt des Premiers Pas. Dans cette forêt, elle devra répondre à des questions pour découvrir les cartes, les joueurs et apprendre à jouer avec un partenaire. Si Luna réussit toutes les épreuves de la forêt, elle obtiendra la Potion des Fondations. Es-tu prêt.e à l’aider ?",
    "Leçon 01",
    "Le grimoire du Petit Bridge"
   ]
  },
  {
   "id": "75b307ab-cec5-4c6a-ac2f-397a5b9c22ab",
   "order": 4,
   "name": "1.1",
   "popup": false,
   "texts": [
    "Question 1/4",
    "Voici les cartes du jeu Petit Bridge"
   ],
   "activity": {
    "type": "QUIZ_ACTIVITY",
    "question": "Combien y a-t-il de familles (couleurs) dans le jeu de cartes du Petit Bridge ?",
    "answers": [
     {
      "text": "1 famille",
      "correct": false,
      "order": null
     },
     {
      "text": "2 familles",
      "correct": false,
      "order": null
     },
     {
      "text": "4 familles",
      "correct": true,
      "order": null
     },
     {
      "text": "5 familles",
      "correct": false,
      "order": null
     }
    ],
    "feedbackOk": "Bravo !",
    "feedbackKo": "Attention ! Regarde bien les cartes affichées. Combien de couleurs différentes vois-tu ?"
   }
  },
  {
   "id": "551f03f3-bd02-4386-a734-26c2fc9fea5e",
   "order": 5,
   "name": "1.2",
   "popup": false,
   "texts": [
    "Les cartes sont rangées dans l'ordre croissant de la plus faible à la plus forte",
    "Question 2/4"
   ],
   "activity": {
    "type": "QUIZ_ACTIVITY",
    "question": "Quelle est la carte la plus forte dans une couleur ?",
    "answers": [
     {
      "text": "le 9",
      "correct": false,
      "order": null
     },
     {
      "text": "le 5",
      "correct": false,
      "order": null
     },
     {
      "text": "le 10",
      "correct": true,
      "order": null
     },
     {
      "text": "le 1",
      "correct": false,
      "order": null
     }
    ],
    "feedbackOk": "Bravo !",
    "feedbackKo": "Attention ! Regarde bien les cartes affichées. Quelle est la carte avec le nombre le plus grand ?"
   }
  },
  {
   "id": "412011e6-82c8-4ec9-93bf-a955dc92d170",
   "order": 6,
   "name": "1.3",
   "popup": false,
   "texts": [
    "Au bridge, on joue à deux contre deux. Les partenaires sont en face l’un de l’autre, autour d’un tapis sur lequel sont indiqués les points cardinaux.",
    "Question 3/4"
   ],
   "activity": {
    "type": "QUIZ_ACTIVITY",
    "question": "Qui est le partenaire de Luna, en Nord ?",
    "answers": [
     {
      "text": "Ouest",
      "correct": false,
      "order": null
     },
     {
      "text": "Est",
      "correct": false,
      "order": null
     },
     {
      "text": "Sud",
      "correct": true,
      "order": null
     }
    ],
    "feedbackOk": "Bravo !",
    "feedbackKo": "Attention ! Regarde bien l'image. Quel est le joueur placé en face du joueur Nord ?"
   }
  },
  {
   "id": "13eed9f3-c1c2-4e60-a09f-801f26b88141",
   "order": 7,
   "name": "1.4",
   "popup": false,
   "texts": [
    "Question 4/4"
   ],
   "activity": {
    "type": "FILL_IN_THE_BLANKS_ACTIVITY",
    "question": "Remplissez les blancs avec les bonnes réponses.",
    "answers": [
     {
      "text": "Ouest",
      "correct": false,
      "order": 5
     },
     {
      "text": "Est",
      "correct": false,
      "order": 4
     },
     {
      "text": "partenaire",
      "correct": false,
      "order": 3
     },
     {
      "text": "équipe",
      "correct": false,
      "order": 2
     },
     {
      "text": "10",
      "correct": false,
      "order": 1
     },
     {
      "text": "40",
      "correct": false,
      "order": 0
     }
    ],
    "feedbackOk": "Bravo ! Tu es prêt.e pour la suite des aventures",
    "feedbackKo": "Attention ! Aide toi des images..."
   }
  },
  {
   "id": "7ba0dff2-a163-4d1e-be21-f14708169bad",
   "order": 8,
   "name": "CORRECT 1",
   "popup": false,
   "texts": [
    "Continue",
    "Tu as découvert le matériel pour jouer au Petit Bridge. Tu permets à Luna de récupérer la Potion des Fondations.",
    "Bravo!",
    "La potion des Fondations"
   ]
  },
  {
   "id": "c78e738d-13ea-4403-b39f-b5aa21e14891",
   "order": 9,
   "name": "MENU 2",
   "popup": false,
   "texts": [
    "La deuxième leçon conduit Luna dans la Grotte des Jeux Secrets. Dans cette grotte mystérieuse, elle devra apprendre à jouer une carte,à comprendre comment gagner une levée et à savoir quoi faire quand elle n’a pas la bonne couleur. Si Luna réussit toutes les épreuves de la grotte, elle obtiendra la Potion des Levées",
    "Leçon 02",
    "Le grimoire du Petit Bridge"
   ]
  },
  {
   "id": "22c81fcd-2d61-4730-a7c2-25ec0b84953a",
   "order": 10,
   "name": "2.1",
   "popup": false,
   "texts": [
    "Ouest est le joueur qui a distribué les cartes. Il entame et pose la première carte. Il met un 7 vert. Tous les autres joueurs mettent une carte verte. Parmi les cartes vertes de Luna, choisis toi aussi une carte et pose la sur la table.",
    "Jeu de Luna",
    "Question 1/4",
    "Règle 1"
   ]
  },
  {
   "id": "5968dea4-b0a6-4f89-80fb-c5b0faa48f3b",
   "order": 11,
   "name": "2.2",
   "popup": false,
   "texts": [
    "Règle 2",
    "Question 2/4",
    "Une carte jaune a été posée en premier sur la table. Tous les joueurs ont joué une carte jaune de leur jeu."
   ],
   "activity": {
    "type": "QUIZ_ACTIVITY",
    "question": "À ton avis, qui a gagné la levée ?",
    "answers": [
     {
      "text": "Ouest",
      "correct": false,
      "order": null
     },
     {
      "text": "Nord",
      "correct": true,
      "order": null
     },
     {
      "text": "Est",
      "correct": false,
      "order": null
     },
     {
      "text": "Sud",
      "correct": false,
      "order": null
     }
    ],
    "feedbackOk": "Bravo !",
    "feedbackKo": "Attention ! Regarde bien qui a posé la carte la plus forte."
   }
  },
  {
   "id": "79a07f39-4f31-4642-bdff-5d22879978b3",
   "order": 12,
   "name": "2.3",
   "popup": false,
   "texts": [
    "Jeu de Luna",
    "Question 3/4",
    "Nord a gagné la levée avec le 8 jaune. C'est lui qui rejoue. Il pose maintenant un 2 rouge. Est pose une carte rouge. Luna n'a pas de carte rouge. Parmi les cartes de son jeu, choisis une carte à poser sur la table.",
    "Règle 3"
   ]
  },
  {
   "id": "39e0481f-2b3a-484a-b70a-b7116203e68a",
   "order": 13,
   "name": "2.4",
   "popup": false,
   "texts": [
    "Question 4/4"
   ],
   "activity": {
    "type": "FILL_IN_THE_BLANKS_ACTIVITY",
    "question": "Remplissez les blancs avec les bonnes réponses.",
    "answers": [
     {
      "text": "carte",
      "correct": false,
      "order": 0
     },
     {
      "text": "forte",
      "correct": false,
      "order": 2
     },
     {
      "text": "levée",
      "correct": false,
      "order": 1
     },
     {
      "text": "défausse",
      "correct": false,
      "order": 4
     },
     {
      "text": "couleur",
      "correct": false,
      "order": 3
     },
     {
      "text": "rejoue.",
      "correct": false,
      "order": 5
     }
    ],
    "feedbackOk": "Bravo ! Tu es prêt.e pour la suite des aventures",
    "feedbackKo": "Attention ! Rappelle toi des règles que l'on a découvert ensemble..."
   }
  },
  {
   "id": "fb64b39c-e682-49e0-b54c-3d6dedfc3489",
   "order": 14,
   "name": "CORRECT 2",
   "popup": false,
   "texts": [
    "La potion des Levées",
    "Continue",
    "Tu as appris comment jouer les cartes au Petit Bridge et gagner une levée. Tu permets à Luna de récupérer la Potion des Levées .",
    "Bravo !"
   ]
  },
  {
   "id": "b2c34569-5e6d-4e01-89ea-b6bb11a61749",
   "order": 15,
   "name": "MENU 3",
   "popup": false,
   "texts": [
    "Luna entre maintenant dans la Salle des duos magiques. Dans cette salle, elle va apprendre une règle très importante du Petit Bridge : on ne joue jamais seul. Pour réussir cette leçon, Luna devra comprendre comment jouer avec son partenaire, gagner des levées ensemble et aider son équipe. Si elle réussit toutes les épreuves de la salle, elle pourra récupérer la Potion des partenaires . Es-tu prêt.e à l’aider à jouer en équipe ?",
    "Leçon 03",
    "Le grimoire du Petit Bridge"
   ]
  },
  {
   "id": "7ff1c552-96fe-4167-a102-1094b6c9b971",
   "order": 16,
   "name": "3.1",
   "popup": false,
   "texts": [
    "Ce n'est pas la bonne réponse. Regarde bien la carte posée par ton partenaire en Nord. Recommence !",
    "Règle 4",
    "Luna a démarré une partie de Petit Bridge avec ses camarades de classe. Quelle carte conseilles-tu à Luna, placée en Sud, de jouer ?",
    "Question 1/4"
   ]
  },
  {
   "id": "d287bcb6-1727-49a3-aded-b2ec30e8e7f4",
   "order": 17,
   "name": "3.2",
   "popup": false,
   "texts": [
    "Bravo ! Ton partenaire ne peut pas gagner la levée avec sa carte. À toi de mettre ton 8 pour faire gagner ton équipe !",
    "Ce n'est pas la bonne réponse. Regarde bien la carte posée par ton partenaire en Nord. Recommence !",
    "Question 2/4",
    "Luna a démarré une partie de Petit Bridge avec ses camarades de classe. Quelle carte conseilles-tu à Luna, placée en Sud, de jouer ?"
   ]
  },
  {
   "id": "691201ac-7bc1-48de-9c26-e21d65a60c6c",
   "order": 18,
   "name": "3.3",
   "popup": false,
   "texts": [
    "Ce n'est pas la bonne réponse. Observe bien l'ensemble des cartes restant dans les mains de chaque joueur. Recommence !",
    "Règle 5",
    "Question 3/4",
    "Le partenaire de Luna joue le 8 jaune. À ton avis, que jouerais-tu si tu étais en Est ? Que jouerait Luna, placée en Sud ?"
   ]
  },
  {
   "id": "6f08499d-7e99-43d5-bccc-3d196fd56353",
   "order": 19,
   "name": "3.4",
   "popup": false,
   "texts": [
    "Question 4/4"
   ],
   "activity": {
    "type": "FILL_IN_THE_BLANKS_ACTIVITY",
    "question": "Remplissez les blancs avec les bonnes réponses.",
    "answers": [
     {
      "text": "grosse",
      "correct": false,
      "order": 2
     },
     {
      "text": "gaspiller",
      "correct": false,
      "order": 3
     },
     {
      "text": "partenaire",
      "correct": false,
      "order": 1
     },
     {
      "text": "fin",
      "correct": false,
      "order": 4
     },
     {
      "text": "équipe",
      "correct": false,
      "order": 0
     },
     {
      "text": "perdre",
      "correct": false,
      "order": 5
     }
    ],
    "feedbackOk": "Bravo ! Tu es prêt.e pour la suite des aventures",
    "feedbackKo": "Attention ! Rappelle toi des règles que l'on a découvert ensemble..."
   }
  },
  {
   "id": "da5cbf73-37db-4a0d-a13b-634d7c05c95a",
   "order": 20,
   "name": "CORRECT 3",
   "popup": false,
   "texts": [
    "Tu as appris à jouer avec ton partenaire au Petit Bridge. Tu sais maintenant qu’on joue ensemble pour gagner des levées. Tu permets à Luna de récupérer la Potion des Partenaires .",
    "La potion des Partenaires",
    "Bravo !",
    "Continue"
   ]
  },
  {
   "id": "f3557583-fb65-4d32-8894-a9569affd408",
   "order": 21,
   "name": "MENU 3 Copy",
   "popup": false,
   "texts": [
    "Luna entre dans la Bibliothèque des Dernières Leçons. Ici, un joueur pose ses cartes face visible sur la table : c’est l’endormi.Son partenaire devient alors le pilote de l’équipe et décide des cartes à jouer pour les deux joueurs. Si Luna réussit cette épreuve, elle récupérera la dernière potiondu Grimoire du Petit Bridge : la Potion de l’Endormi . Es-tu prêt.e à l’aider ?",
    "Leçon 04",
    "Le grimoire du Petit Bridge"
   ]
  },
  {
   "id": "12dfc389-cdad-4df8-ae08-089c67f77b00",
   "order": 22,
   "name": "4.1",
   "popup": false,
   "texts": [
    "Tu joues pour Ouest et pose le 8 vert sur la table. Le jeu de l'endormi se dévoile et Luna joue pour son partenaire. Pose la carte demandée sur la table et clique sur VÉRIFICATION",
    "Pose le 4 vert !",
    "Clique ICI",
    "Règle 6",
    "Question 1/4"
   ]
  },
  {
   "id": "30613d8b-9fb3-48af-b18b-448e79f97df6",
   "order": 23,
   "name": "4.3",
   "popup": false,
   "texts": [
    "Question 2/4"
   ],
   "activity": {
    "type": "IMAGE_ACTIVITY",
    "question": "Nord est endormi. Comment jouerais-tu à la place d'Est ?",
    "answers": [
     {
      "text": "",
      "correct": true,
      "order": null
     },
     {
      "text": "",
      "correct": false,
      "order": null
     }
    ],
    "feedbackOk": "",
    "feedbackKo": "Non, ce n'est pas le meilleur choix."
   }
  },
  {
   "id": "9f7caa94-e14b-4d42-a5b8-a3dc9e5916e8",
   "order": 24,
   "name": "4.3",
   "popup": false,
   "texts": [
    "Question 3/4",
    "C'est à Luna de poser une carte. Elle joue avec le jeu de l'Endormi en Nord. Trouve l'ordre dans lequel elle doit jouer ses cartes pour que son équipe gagne 4 levées sans connaitre les cartes des adversaires.",
    "Attention, tu n'as pas commencé par la bonne carte. Recommence."
   ]
  },
  {
   "id": "0c33ceb9-bde4-435e-8df2-b19f61a4670f",
   "order": 25,
   "name": "4.4",
   "popup": false,
   "texts": [
    "Question 4/4"
   ],
   "activity": {
    "type": "FILL_IN_THE_BLANKS_ACTIVITY",
    "question": "Remplissez les blancs avec les bonnes réponses.",
    "answers": [
     {
      "text": "décide",
      "correct": false,
      "order": 4
     },
     {
      "text": "entame",
      "correct": false,
      "order": 0
     },
     {
      "text": "visible",
      "correct": false,
      "order": 3
     },
     {
      "text": "gauche",
      "correct": false,
      "order": 1
     },
     {
      "text": "endormi",
      "correct": false,
      "order": 2
     }
    ],
    "feedbackOk": "Bravo ! Tu es prêt.e pour la suite des aventures",
    "feedbackKo": "Attention ! Rappelle toi des règles que l'on a découvert ensemble..."
   }
  },
  {
   "id": "49b9a96c-b21b-4eac-ab36-a0c339336146",
   "order": 26,
   "name": "CORRECT 4",
   "popup": false,
   "texts": [
    "Tu as aidé Luna à récupérer la dernière potion : la Potion de l'Endormi . Luna a terminé toutes les leçons du Grimoire du Petit Bridge. Elle connait les règles essentielles du jeu : les cartes, les levées, le jeu d'équipe et le rôle de l'endormi.",
    "FÉLICIATIONS !",
    "Le grimoire du Petit Bridge"
   ]
  },
  {
   "id": "1a943fe1-d2cc-4eab-952d-7f9de781cb39",
   "order": 27,
   "name": "FINAL",
   "popup": false,
   "texts": [
    "Il est maintenant temps de passer au jeu réel !"
   ]
  },
  {
   "id": "88761768-1922-4696-bde4-2cbd461f53f9",
   "order": 28,
   "name": "EXIT",
   "popup": false,
   "texts": [
    "Je continue",
    "J'arrête",
    "Si tu quittes le jeu maintenant, tu ne découvriras pas tous les secrets du Petit Bridge.",
    "Es-tu sur de vouloir arrêter l'aventure ?"
   ]
  },
  {
   "id": "273005c0-457f-40dd-b1a0-13b64ccc4793",
   "order": 29,
   "name": "Copie Copie",
   "popup": true,
   "texts": [
    "Réponse à l'exercice : Ici Est ne peut pas gagner donc il doit mettre sa petite carte. Sud doit jouer le 10 jaune sinon Ouest va gagner avec son 9 jaune.",
    "Règle 5",
    "Bravo ! 🎉",
    "Attention, jouer sans gaspiller ne veut pas forcément dire garder ses grosses cartes pour la fin !"
   ]
  },
  {
   "id": "28f5ed17-70d2-4029-b796-0f93a979520c",
   "order": 30,
   "name": "Copie Copie",
   "popup": true,
   "texts": [
    "Exemple : Si la couleur demandée est du rouge et que je n'ai pas cette couleur dans mon jeu, mon 9 jaune ne pourra pas gagner la levée. Il est préférable de mettre une petite carte comme le 2 vert par exemple.",
    "Règle 3",
    "Bravo ! 🎉",
    "Si on n’a pas de carte de la couleur demandée, on se \"défausse\" d’une carte d’une autre couleur mais elle ne peut pas gagner la levée."
   ]
  },
  {
   "id": "4ae95e6b-283e-4783-97bb-5249aa12242e",
   "order": 31,
   "name": "Copie",
   "popup": true,
   "texts": [
    "Le Petit Bridge est un jeu d'équipe : il faut jouer sans gaspiller !",
    "Règle 4",
    "Bravo ! 🎉",
    "Je joue en équipe. Je dois être attentif aux cartes jouées par mon partenaire. S'il va gagner la levée, la meilleure tactique n'est pas de jouer ma plus grosse carte. Je peux la garder pour plus tard pour faire une autre levée."
   ]
  },
  {
   "id": "58e3a383-70dc-491a-a840-0f77dacf96ec",
   "order": 32,
   "name": "Copie",
   "popup": true,
   "texts": [
    "Exemple : Si la première carte posée sur la table est une carte verte alors on est obligé de jouer une carte verte présente dans son jeu.",
    "Règle 1",
    "Bravo ! 🎉",
    "Il faut jouer la couleur demandée par la première carte posée sur la table."
   ]
  },
  {
   "id": "d3d0d916-eb44-4b1c-827c-e2b2af58e483",
   "order": 33,
   "name": "Copie",
   "popup": true,
   "texts": [
    "Mémo Une levée est l'ensemble des 4 cartes jouées par chaque joueur. A chaque partie, il y a, au maximum, 10 levées à réaliser.",
    "Règle 2",
    "Bravo ! 🎉",
    "Le joueur qui a posé la plus forte carte gagne la levée. Il rejoue pour la levée suivante.",
    "Le but du jeu est de faire plus de levées que les adversaires."
   ]
  },
  {
   "id": "f9cedbec-bc0d-45ed-871a-ac5d853e2fdf",
   "order": 34,
   "name": "Copie Copie Copie Copie",
   "popup": true,
   "texts": [
    "Entame : c'est la première carte jouée de la partie.",
    "Règle 6",
    "Bravo ! 🎉",
    "Lorsque la carte d'entame est posée sur la table, le joueur à gauche étale son jeu face visible. Il devient l' Endormi pour la durée de la partie. C'est son partenaire qui décide et lui indique quelles cartes jouer."
   ]
  }
 ]
};
