#!/usr/bin/env python3
"""Build extension/gamedata.js from the Genially view API JSON.

Usage: python3 tools/build_gamedata.py [path/to/genially_api.json]
The output embeds the full slide/text/activity model for the game so the
extension works even if the runtime API fetch fails.
"""
import json
import re
import html
import sys
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "extension/gamedata.js"

# (genially id, api json dump) - run: curl .../api/view/<id> -o <file>
GAMES = [
    ("697f6a08ef130744478db916", ROOT / ".tmp/view.json"),
    ("6999b0b9d1e83ea5a328b462", ROOT / ".tmp/genially_api_ep2.json"),
]


def strip_html(s):
    if not s:
        return ""
    s = re.sub(r"<style[^>]*>.*?</style>", " ", s, flags=re.S)
    s = re.sub(r"<[^>]+>", " ", s)
    s = html.unescape(s)
    return re.sub(r"\s+", " ", s).strip()


def build(genially_id, src):
    data = json.loads(src.read_text())

    texts_by_slide = {}
    for t in data["Texts"] + data["RichContents"]:
        sid = t.get("IdSlide")
        msg = strip_html(t.get("TextMessage") or t.get("Html") or "")
        if sid and msg:
            order = t.get("ReadingOrder") or 99
            texts_by_slide.setdefault(sid, []).append((order, msg))

    activities = {}
    for a in data["Activities"]:
        opts = a.get("Options") or {}
        # Fill-in-the-blanks: the gap sentence lives in Text with
        # <blank-react-node> markers; keep gaps as a ___ token that the
        # extension replaces with a spoken word ("trou" / "blank").
        blanks = ""
        if a["Type"] == "FILL_IN_THE_BLANKS_ACTIVITY" and a.get("Text"):
            raw = re.sub(r"<blank-react-node[^>]*></blank-react-node>", " ___ ", a["Text"])
            raw = re.sub(r"<blank-react-node[^>]*/>", " ___ ", raw)
            blanks = strip_html(raw)
        activities[a["IdSlide"]] = {
            "type": a["Type"],
            "question": strip_html(a["Question"]),
            "blanks": blanks,
            "answers": [
                {
                    "text": strip_html(x.get("Text", "")),
                    "correct": bool(x.get("IsCorrect")),
                    "order": x.get("CorrectOrder"),
                }
                for x in a["Answers"]
            ],
            "feedbackOk": strip_html(opts.get("CorrectAnswerFeedback", "")),
            "feedbackKo": strip_html(opts.get("IncorrectAnswerFeedback", "")),
        }

    slides = []
    visible = [s for s in data["Slides"] if not s["Hidden"]]
    for s in sorted(visible, key=lambda x: x["Order"]):
        entry = {
            "id": s["Id"],
            "order": s["Order"],
            "name": (s["Name"] or "").strip(),
            "popup": bool(s.get("Popup")),
            "texts": [m for _, m in sorted(texts_by_slide.get(s["Id"], []))],
        }
        if s["Id"] in activities:
            entry["activity"] = activities[s["Id"]]
        slides.append(entry)

    return {
        "geniallyId": genially_id,
        "title": data["Genially"]["Name"],
        "lang": "fr",
        "total": sum(1 for s in slides if not s["popup"]),
        "slides": slides,
    }


def main():
    games = {gid: build(gid, src) for gid, src in GAMES}
    js = "// Generated by tools/build_gamedata.py - do not edit by hand\n"
    js += "window.PBA_GAMES = " + json.dumps(games, ensure_ascii=False, indent=1) + ";\n"
    OUT.write_text(js)
    print(f"wrote {OUT} ({len(js)} bytes, "
          + ", ".join(f"{gid[:6]}:{len(m['slides'])} slides" for gid, m in games.items()) + ")")


if __name__ == "__main__":
    main()
