#!/usr/bin/env python3
"""Pre-generates neural audio (Microsoft Edge TTS voices, free, no key) for
every static sentence the extension can speak, and writes the lookup map
extension/audio-map.js used by content.js. Each game has its own narrator
voice profile ('f' = female, episode 1; 'm' = male, episode 2).

Usage:
    node tools/extract_segments.mjs
    uv run --with edge-tts python3 tools/build_audio.py
"""
import asyncio
import hashlib
import json
import pathlib

import edge_tts

ROOT = pathlib.Path(__file__).resolve().parent.parent
SEGS = json.loads((ROOT / ".tmp/segments.json").read_text())
AUDIO = ROOT / "extension/audio"
AUDIO.mkdir(exist_ok=True)

# Not *Multilingual voices for French: those auto-detect the language per
# segment and read short French labels with an English accent.
# EN keeps multilingual voices on purpose: the en| sets still contain
# untranslated French texts they must be able to read.
VOICES = {
    "f": {"fr": "fr-FR-DeniseNeural", "en": "en-US-AvaMultilingualNeural"},
    "m": {"fr": "fr-FR-HenriNeural", "en": "en-US-AndrewMultilingualNeural"},
}

# What the voice should actually pronounce, when the raw text misleads the
# voice. Map keys stay the raw text (content.js looks them up).
NUM_FR = {"1": "un", "2": "deux", "3": "trois", "4": "quatre", "5": "cinq",
          "6": "six", "7": "sept", "8": "huit", "9": "neuf"}


def spoken(lang, text):
    if lang == "fr" and text in NUM_FR:
        return NUM_FR[text]
    # ALL-CAPS labels (DÉMARRER, START...) get spelled out or mangled by the
    # voice; speak them in sentence case instead.
    if len(text) >= 3 and text.isupper():
        return text[0] + text[1:].lower()
    return text


def fname(profile, lang, text):
    return hashlib.sha1(f"{profile}|{lang}|{text}".encode()).hexdigest()[:16] + ".mp3"


sem = asyncio.Semaphore(8)


async def gen(profile, lang, text):
    f = AUDIO / fname(profile, lang, text)
    if f.exists() and f.stat().st_size > 0:
        return True
    async with sem:
        for attempt in range(3):
            try:
                await edge_tts.Communicate(spoken(lang, text), VOICES[profile][lang]).save(str(f))
                if f.exists() and f.stat().st_size > 0:
                    return True
            except Exception:
                await asyncio.sleep(2 * (attempt + 1))
    print("FAILED", profile, lang, text[:70])
    return False


async def main():
    # one generation per unique (profile, lang, text)
    uniq = {(s["profile"], s["lang"], s["text"]) for s in SEGS}
    results = await asyncio.gather(*(gen(*u) for u in uniq))

    # per-game lookup maps: "<lang>|<text>" -> file
    games = {}
    for s in SEGS:
        f = AUDIO / fname(s["profile"], s["lang"], s["text"])
        if f.exists() and f.stat().st_size > 0:
            games.setdefault(s["game"], {})[f'{s["lang"]}|{s["text"]}'] = f.name

    js = (
        "// Generated by tools/build_audio.py - do not edit\n"
        "window.PBA_AUDIO = " + json.dumps(games, ensure_ascii=False, indent=1) + ";\n"
    )
    (ROOT / "extension/audio-map.js").write_text(js)
    # prune orphan files no longer referenced
    referenced = {n for m in games.values() for n in m.values()}
    pruned = 0
    for f in AUDIO.glob("*.mp3"):
        if f.name not in referenced:
            f.unlink()
            pruned += 1
    total = sum(f.stat().st_size for f in AUDIO.glob("*.mp3"))
    print(f"{sum(results)}/{len(uniq)} segments ok, "
          + ", ".join(f"{g[:6]}: {len(m)} entries" for g, m in games.items())
          + f", {total / 1e6:.1f} MB, pruned {pruned}")


asyncio.run(main())
