#!/usr/bin/env python3
"""Build extension/gamedata.js from the Genially view API JSON.

Usage: python3 tools/build_gamedata.py [path/to/genially_api.json]
The output embeds the full slide/text/activity model for the game so the
extension works even if the runtime API fetch fails.
"""
import json
import re
import html
import sys
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / ".tmp/genially_api.json"
OUT = ROOT / "extension/gamedata.js"

GENIALLY_ID = "697f6a08ef130744478db916"


def strip_html(s):
    if not s:
        return ""
    s = re.sub(r"<style[^>]*>.*?</style>", " ", s, flags=re.S)
    s = re.sub(r"<[^>]+>", " ", s)
    s = html.unescape(s)
    return re.sub(r"\s+", " ", s).strip()


def main():
    data = json.loads(SRC.read_text())

    texts_by_slide = {}
    for t in data["Texts"] + data["RichContents"]:
        sid = t.get("IdSlide")
        msg = strip_html(t.get("TextMessage") or t.get("Html") or "")
        if sid and msg:
            order = t.get("ReadingOrder") or 99
            texts_by_slide.setdefault(sid, []).append((order, msg))

    activities = {}
    for a in data["Activities"]:
        opts = a.get("Options") or {}
        activities[a["IdSlide"]] = {
            "type": a["Type"],
            "question": strip_html(a["Question"]),
            "answers": [
                {
                    "text": strip_html(x.get("Text", "")),
                    "correct": bool(x.get("IsCorrect")),
                    "order": x.get("CorrectOrder"),
                }
                for x in a["Answers"]
            ],
            "feedbackOk": strip_html(opts.get("CorrectAnswerFeedback", "")),
            "feedbackKo": strip_html(opts.get("IncorrectAnswerFeedback", "")),
        }

    slides = []
    visible = [s for s in data["Slides"] if not s["Hidden"]]
    for s in sorted(visible, key=lambda x: x["Order"]):
        entry = {
            "id": s["Id"],
            "order": s["Order"],
            "name": (s["Name"] or "").strip(),
            "popup": bool(s.get("Popup")),
            "texts": [m for _, m in sorted(texts_by_slide.get(s["Id"], []))],
        }
        if s["Id"] in activities:
            entry["activity"] = activities[s["Id"]]
        slides.append(entry)

    model = {
        "geniallyId": GENIALLY_ID,
        "title": data["Genially"]["Name"],
        "lang": "fr",
        "total": sum(1 for s in slides if not s["popup"]),
        "slides": slides,
    }

    js = "// Generated by tools/build_gamedata.py - do not edit by hand\n"
    js += "window.PBA_GAMEDATA = " + json.dumps(model, ensure_ascii=False, indent=1) + ";\n"
    OUT.write_text(js)
    print(f"wrote {OUT} ({len(js)} bytes, {len(slides)} slides)")


if __name__ == "__main__":
    main()
