#!/usr/bin/env python3
"""Pre-generates neural audio (Microsoft Edge TTS voices, free, no key) for
every static sentence the extension can speak, and writes the lookup map
extension/audio-map.js used by content.js.

Usage:
    node tools/extract_segments.mjs
    uv run --with edge-tts python3 tools/build_audio.py
"""
import asyncio
import hashlib
import json
import pathlib

import edge_tts

ROOT = pathlib.Path(__file__).resolve().parent.parent
SEGS = json.loads((ROOT / ".tmp/segments.json").read_text())
AUDIO = ROOT / "extension/audio"
AUDIO.mkdir(exist_ok=True)

VOICES = {
    "fr": "fr-FR-VivienneMultilingualNeural",
    "en": "en-US-AvaMultilingualNeural",
}

# What the voice should actually pronounce, when the raw text misleads the
# multilingual voice. Map keys stay the raw text (content.js looks them up).
NUM_FR = {"1": "un", "2": "deux", "3": "trois", "4": "quatre", "5": "cinq",
          "6": "six", "7": "sept", "8": "huit", "9": "neuf"}


def spoken(lang, text):
    if lang == "fr" and text in NUM_FR:
        return NUM_FR[text]
    # ALL-CAPS labels (DÉMARRER, START...) get spelled out or mangled by the
    # voice; speak them in sentence case instead.
    if len(text) >= 3 and text.isupper():
        return text[0] + text[1:].lower()
    return text


def key(lang, text):
    return f"{lang}|{text}"


def fname(lang, text):
    return hashlib.sha1(key(lang, text).encode()).hexdigest()[:16] + ".mp3"


sem = asyncio.Semaphore(8)


async def gen(lang, text):
    f = AUDIO / fname(lang, text)
    if f.exists() and f.stat().st_size > 0:
        return True
    async with sem:
        for attempt in range(3):
            try:
                await edge_tts.Communicate(spoken(lang, text), VOICES[lang]).save(str(f))
                if f.exists() and f.stat().st_size > 0:
                    return True
            except Exception:
                await asyncio.sleep(2 * (attempt + 1))
    print("FAILED", lang, text[:70])
    return False


async def main():
    results = await asyncio.gather(*(gen(s["lang"], s["text"]) for s in SEGS))
    mapping = {
        key(s["lang"], s["text"]): fname(s["lang"], s["text"])
        for s in SEGS
        if (AUDIO / fname(s["lang"], s["text"])).exists()
        and (AUDIO / fname(s["lang"], s["text"])).stat().st_size > 0
    }
    js = (
        "// Generated by tools/build_audio.py - do not edit\n"
        "window.PBA_AUDIO = " + json.dumps(mapping, ensure_ascii=False, indent=1) + ";\n"
    )
    (ROOT / "extension/audio-map.js").write_text(js)
    # prune orphan files no longer referenced
    referenced = set(mapping.values())
    pruned = 0
    for f in AUDIO.glob("*.mp3"):
        if f.name not in referenced:
            f.unlink()
            pruned += 1
    total = sum(f.stat().st_size for f in AUDIO.glob("*.mp3"))
    print(f"{sum(results)}/{len(SEGS)} segments ok, map: {len(mapping)} entries, "
          f"{total / 1e6:.1f} MB, pruned {pruned}")


asyncio.run(main())
